name: Build and Push Docker Image

on:
    workflow_dispatch:
    push:
        branches:
            - master

env:
    # ghcr.io | registry.gitlab.com
    DOCKER_REGISTRY: ghcr.io
    # github.repository as <account>/<repo>
    DOCKER_REPOSITORY: ${{ github.repository }}

jobs:
    build-and-push-docker:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.DOCKER_REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  # username: ${{ secrets.DOCKER_USERNAME }}
                  # password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Get short SHA of last commit
              id: git
              run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Set docker repository to lowercase
              run: echo "DOCKER_REPOSITORY=${DOCKER_REPOSITORY,,}" >> ${GITHUB_ENV}

            - name: Build and push docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:latest
                      ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ steps.git.outputs.short_sha }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
